# Generated by Django 4.1 on 2022-09-24 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=20, verbose_name='numero_tarjeta')),
                ('cvv', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='cvv')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('fecha_expiracion', models.DateField(verbose_name='fecha_expiracion')),
                ('marca', models.CharField(choices=[('V', 'VISA'), ('M', 'MASTERCARD')], max_length=2)),
                ('tipo', models.CharField(choices=[('C', 'CREDITO'), ('D', 'DEBITO')], max_length=2)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
                'db_table': 'Tarjeta',
            },
        ),
    ]