# Generated by Django 4.1 on 2022-09-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('HTO', 'HIPOTECARIO'), ('PDO', 'PRENDARIO'), ('PRL', 'PERSONAL')], default='HTO', max_length=3)),
                ('Fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('Total', models.IntegerField(verbose_name='Total')),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]